# Generated by Django 4.0.3 on 2022-04-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dates',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Month', models.CharField(max_length=12)),
                ('Day', models.IntegerField()),
                ('Fact', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Months',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Month', models.CharField(max_length=12)),
                ('DaysChecked', models.IntegerField()),
            ],
        ),
    ]
